export enum ApiRoutes {
  MAP_REGIONS = '/map/regions',
  MAP_MAHALLAS = '/map/mahallas',
  MAP_DISTRICTS = '/map/districts',
  MAP_STREETS = '/map/streets',
  MAP_PROPERTIES = '/map/properties',
  MAP_STATS = '/map/stats',
  REGIONS = '/regions',
  DISTRICTS = '/districts',
  MAHALLAS = '/mahallas',
  STREETS = '/streets',
  PROPERTIES = '/properties',
  LIST_REGIONS = '/regions/list',
  LIST_DISTRICTS = '/districts/list',
}
